"""ETF factor reference library adapted from open-source quant ideas.

The factors in this file are not direct copies of Qlib, WorldQuant 101 Alphas,
or Alphalens. They are simplified ETF-friendly factor templates inspired by:

- Qlib Alpha158 / Alpha360: rolling return, moving average, volatility, volume,
  price-volume relationship, and window features.
- WorldQuant 101 Alphas: formulaic alpha style using rank, lag, rolling mean,
  rolling std, rolling correlation, and price-volume relations.
- Alphalens: factor validation concepts such as IC, quantile return, long-short
  spread, factor turnover, and group analysis.
- ETF / Sector Rotation: momentum, relative strength, volatility control,
  Top-K / Top-percent selection, periodic rebalancing, and equal weighting.

All formulas are written as BigQuant-oriented expressions or pandas hints.
Future returns are labels only and are intentionally excluded from this library.
"""

ETF_FACTOR_LIBRARY: list[dict] = [
    {
        "name": "momentum_5d",
        "description": "ETF 过去 5 个交易日短期价格动量",
        "formula": "close / m_lag(close, 5) - 1",
        "direction": "higher_better",
        "category": "momentum",
        "factor_type": "动量因子",
        "source_ideas": ["Qlib Alpha158 ROC", "Sector Rotation momentum"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "momentum_20d",
        "description": "ETF 过去 20 个交易日中短期价格动量",
        "formula": "close / m_lag(close, 20) - 1",
        "direction": "higher_better",
        "category": "momentum",
        "factor_type": "动量因子",
        "source_ideas": ["Qlib Alpha158 ROC", "Sector Rotation momentum"],
        "bigquant_ready": True,
        "mvp_default": True,
        "uses_future_data": False,
    },
    {
        "name": "momentum_60d",
        "description": "ETF 过去 60 个交易日中期价格动量",
        "formula": "close / m_lag(close, 60) - 1",
        "direction": "higher_better",
        "category": "momentum",
        "factor_type": "动量因子",
        "source_ideas": ["Qlib Alpha158 ROC", "Sector Rotation momentum"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "ma_gap_20d",
        "description": "收盘价相对 20 日均线的位置",
        "formula": "close / m_avg(close, 20) - 1",
        "direction": "higher_better",
        "category": "trend",
        "factor_type": "趋势因子",
        "source_ideas": ["Qlib Alpha158 MA"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "ma_gap_60d",
        "description": "收盘价相对 60 日均线的位置",
        "formula": "close / m_avg(close, 60) - 1",
        "direction": "higher_better",
        "category": "trend",
        "factor_type": "趋势因子",
        "source_ideas": ["Qlib Alpha158 MA"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "trend_strength",
        "description": "5 日均线相对 20 日均线的趋势强度",
        "formula": "m_avg(close, 5) / m_avg(close, 20) - 1",
        "direction": "higher_better",
        "category": "trend",
        "factor_type": "趋势因子",
        "source_ideas": ["Qlib moving average features", "ETF Rotation trend filter"],
        "bigquant_ready": True,
        "mvp_default": True,
        "uses_future_data": False,
    },
    {
        "name": "relative_strength_20d",
        "description": "ETF 过去 20 日收益相对基准指数的超额强度",
        "formula": "etf_return_20d - benchmark_return_20d",
        "direction": "higher_better",
        "category": "relative_strength",
        "factor_type": "动量因子",
        "source_ideas": ["Sector Rotation relative strength"],
        "bigquant_ready": False,
        "pandas_hint": "需要先合并基准指数 20 日收益",
        "mvp_default": True,
        "uses_future_data": False,
    },
    {
        "name": "relative_strength_60d",
        "description": "ETF 过去 60 日收益相对基准指数的中期超额强度",
        "formula": "etf_return_60d - benchmark_return_60d",
        "direction": "higher_better",
        "category": "relative_strength",
        "factor_type": "动量因子",
        "source_ideas": ["Sector Rotation relative strength"],
        "bigquant_ready": False,
        "pandas_hint": "需要先合并基准指数 60 日收益",
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "amount_ratio_20d",
        "description": "当日成交额相对过去 20 日均值的放大程度",
        "formula": "amount / m_avg(amount, 20)",
        "direction": "higher_better",
        "category": "liquidity",
        "factor_type": "量价因子",
        "source_ideas": ["Qlib Alpha158 volume features", "WorldQuant price-volume relationship"],
        "bigquant_ready": True,
        "mvp_default": True,
        "uses_future_data": False,
    },
    {
        "name": "volume_ratio_20d",
        "description": "当日成交量相对过去 20 日均值的放大程度",
        "formula": "volume / m_avg(volume, 20)",
        "direction": "higher_better",
        "category": "liquidity",
        "factor_type": "量价因子",
        "source_ideas": ["Qlib Alpha158 VMA", "WorldQuant volume relationship"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "liquidity_20d",
        "description": "过去 20 日平均成交额，用于流动性过滤或评分",
        "formula": "m_avg(amount, 20)",
        "direction": "higher_better",
        "category": "liquidity",
        "factor_type": "风险因子",
        "source_ideas": ["ETF Rotation liquidity filter"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "volatility_20d",
        "description": "过去 20 日收益率波动率，作为风险惩罚因子",
        "formula": "m_std(close / m_lag(close, 1) - 1, 20)",
        "direction": "lower_better",
        "category": "risk",
        "factor_type": "风险因子",
        "source_ideas": ["Qlib Alpha158 STD", "Sector Rotation volatility control"],
        "bigquant_ready": True,
        "mvp_default": True,
        "uses_future_data": False,
    },
    {
        "name": "volatility_60d",
        "description": "过去 60 日收益率波动率，衡量中期风险",
        "formula": "m_std(close / m_lag(close, 1) - 1, 60)",
        "direction": "lower_better",
        "category": "risk",
        "factor_type": "风险因子",
        "source_ideas": ["Qlib Alpha158 STD", "Sector Rotation volatility control"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "risk_adjusted_momentum_20d",
        "description": "20 日动量除以 20 日波动率，衡量单位风险趋势收益",
        "formula": "(close / m_lag(close, 20) - 1) / (m_std(close / m_lag(close, 1) - 1, 20) + 0.001)",
        "direction": "higher_better",
        "category": "risk_adjusted",
        "factor_type": "风险因子",
        "source_ideas": ["Sector Rotation momentum-volatility", "WorldQuant formulaic composition"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "drawdown_20d",
        "description": "收盘价相对过去 20 日最高价的回撤幅度",
        "formula": "close / m_max(close, 20) - 1",
        "direction": "higher_better",
        "category": "risk",
        "factor_type": "风险因子",
        "source_ideas": ["Qlib rolling MAX", "ETF Rotation drawdown control"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "price_volume_corr_20d",
        "description": "过去 20 日价格收益与成交额变化的滚动相关性",
        "formula": "m_corr(close / m_lag(close, 1) - 1, amount / m_lag(amount, 1) - 1, 20)",
        "direction": "higher_better",
        "category": "price_volume",
        "factor_type": "量价因子",
        "source_ideas": ["Qlib Alpha158 CORR/CORD", "WorldQuant rolling correlation"],
        "bigquant_ready": False,
        "pandas_hint": "若 DAI 不支持 m_corr，可在 pandas 中 groupby instrument 后 rolling corr",
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "price_volume_confirm_20d",
        "description": "20 日动量与成交额放大共同确认的价量因子",
        "formula": "(close / m_lag(close, 20) - 1) * (amount / m_avg(amount, 20))",
        "direction": "higher_better",
        "category": "price_volume",
        "factor_type": "量价因子",
        "source_ideas": ["WorldQuant price-volume relationship", "ETF Rotation confirmation"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "intraday_strength",
        "description": "收盘价在当日高低价区间中的位置，衡量日内强弱",
        "formula": "(close - low) / (high - low + 0.001)",
        "direction": "higher_better",
        "category": "kbar",
        "factor_type": "量价因子",
        "source_ideas": ["Qlib K-bar features", "WorldQuant formulaic OHLC features"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "volume_price_divergence_20d",
        "description": "成交额明显放大但 20 日价格涨幅不高，捕捉量价背离或潜在补涨",
        "formula": "(amount / m_avg(amount, 20)) / (abs(close / m_lag(close, 20) - 1) + 0.001)",
        "direction": "higher_better",
        "category": "price_volume",
        "factor_type": "量价因子",
        "source_ideas": ["WorldQuant price-volume relationship", "量价背离"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "volume_breakout_20d",
        "description": "成交额放大且价格站上 20 日均线，衡量放量突破",
        "formula": "(amount / m_avg(amount, 20)) * (close / m_avg(close, 20) - 1)",
        "direction": "higher_better",
        "category": "breakout",
        "factor_type": "量价因子",
        "source_ideas": ["量价突破", "ETF Rotation trend confirmation"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "reversal_5d",
        "description": "过去 5 日收益的反向值，用于检验短期超跌反弹",
        "formula": "-1 * (close / m_lag(close, 5) - 1)",
        "direction": "higher_better",
        "category": "reversal",
        "factor_type": "反转因子",
        "source_ideas": ["短期反转", "WorldQuant delay/rank style"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "ma_deviation_reversal_20d",
        "description": "价格低于 20 日均线越多，反转得分越高，用于检验均值回归",
        "formula": "-1 * (close / m_avg(close, 20) - 1)",
        "direction": "higher_better",
        "category": "reversal",
        "factor_type": "反转因子",
        "source_ideas": ["均线偏离回归", "Qlib MA"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "rsi_14d",
        "description": "14 日 RSI 强弱指标，用于识别超买超卖；ETF 中建议作为辅助诊断",
        "formula": "100 * m_avg(greatest(close / m_lag(close, 1) - 1, 0), 14) / (m_avg(abs(close / m_lag(close, 1) - 1), 14) + 0.001)",
        "direction": "neutral",
        "category": "reversal",
        "factor_type": "反转因子",
        "source_ideas": ["RSI", "technical reversal"],
        "bigquant_ready": False,
        "pandas_hint": "若 DAI 不支持 greatest，可在 pandas 中计算上涨收益均值 / 绝对收益均值",
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "new_high_distance_60d",
        "description": "当前价格距离 60 日新高的距离，越接近新高代表趋势越强",
        "formula": "close / m_max(close, 60) - 1",
        "direction": "higher_better",
        "category": "trend",
        "factor_type": "动量因子",
        "source_ideas": ["新高距离", "Qlib rolling MAX", "breakout momentum"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "breakout_60d",
        "description": "价格相对过去 60 日最高价的位置，用于识别通道突破",
        "formula": "close / m_max(high, 60) - 1",
        "direction": "higher_better",
        "category": "breakout",
        "factor_type": "趋势因子",
        "source_ideas": ["Donchian breakout", "Qlib rolling MAX"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "ma_alignment_score",
        "description": "均线多头排列强度：5 日均线高于 20 日和 60 日均线时得分更高",
        "formula": "(m_avg(close, 5) / m_avg(close, 20) - 1) + (m_avg(close, 20) / m_avg(close, 60) - 1)",
        "direction": "higher_better",
        "category": "trend",
        "factor_type": "趋势因子",
        "source_ideas": ["均线多头排列", "Qlib MA"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "downside_volatility_20d",
        "description": "过去 20 日下跌收益的波动率，用于衡量下行风险",
        "formula": "m_std(least(close / m_lag(close, 1) - 1, 0), 20)",
        "direction": "lower_better",
        "category": "risk",
        "factor_type": "风险因子",
        "source_ideas": ["downside volatility", "risk control"],
        "bigquant_ready": False,
        "pandas_hint": "若 DAI 不支持 least，可在 pandas 中将正收益截断为 0 后 rolling std",
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "beta_60d",
        "description": "ETF 过去 60 日相对基准收益的 Beta，衡量对大盘波动的敏感度",
        "formula": "cov(etf_return_1d, benchmark_return_1d, 60) / var(benchmark_return_1d, 60)",
        "direction": "lower_better",
        "category": "risk",
        "factor_type": "风险因子",
        "source_ideas": ["Beta risk", "Alphalens group/risk diagnostics"],
        "bigquant_ready": False,
        "pandas_hint": "需要先合并基准指数收益，再按 instrument 计算 rolling cov / rolling var",
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "crowding_amount_ratio_5d",
        "description": "短期成交额暴增程度，用于识别资金拥挤和过热风险",
        "formula": "m_avg(amount, 5) / m_avg(amount, 20)",
        "direction": "lower_better",
        "category": "crowding",
        "factor_type": "风险因子",
        "source_ideas": ["拥挤度", "volume crowding"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "short_term_overheat_5d",
        "description": "短期涨幅过大程度，用于识别追高拥挤风险",
        "formula": "close / m_lag(close, 5) - 1",
        "direction": "lower_better",
        "category": "crowding",
        "factor_type": "风险因子",
        "source_ideas": ["短期过热", "crowding control"],
        "bigquant_ready": True,
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "industry_pe_percentile",
        "description": "ETF 跟踪行业指数 PE 的历史分位数，分位越低估值越便宜",
        "formula": "industry_pe_percentile",
        "direction": "lower_better",
        "category": "valuation",
        "factor_type": "估值因子",
        "source_ideas": ["value factor", "industry valuation"],
        "bigquant_ready": False,
        "pandas_hint": "需要行业指数估值或 ETF 成分股加权估值数据",
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "industry_pb_percentile",
        "description": "ETF 跟踪行业指数 PB 的历史分位数，分位越低估值越便宜",
        "formula": "industry_pb_percentile",
        "direction": "lower_better",
        "category": "valuation",
        "factor_type": "估值因子",
        "source_ideas": ["value factor", "industry valuation"],
        "bigquant_ready": False,
        "pandas_hint": "需要行业指数估值或 ETF 成分股加权估值数据",
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "weighted_roe",
        "description": "ETF 成分股加权 ROE，用于衡量行业 ETF 的盈利质量",
        "formula": "sum(component_weight * component_roe)",
        "direction": "higher_better",
        "category": "quality",
        "factor_type": "质量因子",
        "source_ideas": ["quality factor", "component weighted fundamentals"],
        "bigquant_ready": False,
        "pandas_hint": "需要 ETF 成分股权重和个股 ROE 数据",
        "mvp_default": False,
        "uses_future_data": False,
    },
    {
        "name": "weighted_profit_growth",
        "description": "ETF 成分股加权净利润增长率，用于衡量行业成长性",
        "formula": "sum(component_weight * component_profit_growth)",
        "direction": "higher_better",
        "category": "growth",
        "factor_type": "成长因子",
        "source_ideas": ["growth factor", "component weighted fundamentals"],
        "bigquant_ready": False,
        "pandas_hint": "需要 ETF 成分股权重和个股利润增长数据",
        "mvp_default": False,
        "uses_future_data": False,
    },
]


def get_default_factor_candidates() -> list[dict]:
    """Return the MVP default ETF factor candidates."""
    return [factor.copy() for factor in ETF_FACTOR_LIBRARY if factor["mvp_default"]]


def get_factor_library() -> list[dict]:
    """Return all reference ETF factors."""
    return [factor.copy() for factor in ETF_FACTOR_LIBRARY]


def find_factors_by_categories(categories: set[str]) -> list[dict]:
    """Return factors that belong to the requested categories."""
    return [
        factor.copy()
        for factor in ETF_FACTOR_LIBRARY
        if factor["category"] in categories
    ]
