"""Structured expression knowledge base for AutoETF agent routing.

This module stores common user phrases, their canonical meaning, calculation
rules, and routing hints so the agent can map natural language to executable
research logic more precisely.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional


@dataclass(frozen=True)
class ExpressionEntry:
    id: str
    phrase: str
    canonical_name: str
    expression_type: str
    category: str
    meaning: str
    layer: str = ""
    synonyms: list[str] = field(default_factory=list)
    required_columns: list[str] = field(default_factory=list)
    derived_columns: list[str] = field(default_factory=list)
    formula: str = ""
    calculation_hint: str = ""
    default_window: Optional[int] = None
    optional_windows: list[int] = field(default_factory=list)
    operator: str = ""
    threshold: Any = None
    threshold_type: str = ""
    data_dependency: str = "ohlcv"
    time_direction: str = "current"
    can_be_condition: bool = False
    can_be_factor: bool = False
    can_be_target: bool = False
    leakage_risk: bool = False
    route_to: list[str] = field(default_factory=list)
    ambiguity_level: str = "low"
    fallback_policy: str = "manual_review"
    example_queries: list[str] = field(default_factory=list)
    related_expressions: list[str] = field(default_factory=list)
    correlated_with: list[str] = field(default_factory=list)
    negative_cases: list[str] = field(default_factory=list)
    route_intent: list[str] = field(default_factory=list)
    interpretation: dict[str, str] = field(default_factory=dict)
    knowledge_status: str = "known"
    implementation_status: str = "implemented"
    implementation_key: str = ""
    selection_group: str = ""
    selection_priority: int = 50
    required_context: list[str] = field(default_factory=list)


FACTOR_TERM_MAP: dict[str, list[str]] = {
    "20日动量": ["momentum_20d"],
    "月度动量": ["momentum_20d"],
    "近期动量": ["momentum_20d"],
    "短期动量": ["momentum_5d"],
    "60日动量": ["momentum_60d"],
    "相对强度": ["relative_strength_20d"],
    "相对强弱": ["relative_strength_20d"],
    "低波动": ["volatility_20d"],
    "成交额放大": ["amount_ratio_20d"],
    "成交量放大": ["volume_ratio_20d"],
    "趋势走强": ["trend_strength"],
    "站上20日线": ["ma_gap_20d"],
    "突破前高": ["breakout_60d"],
    "缩量上涨": ["reversal_5d", "amount_ratio_20d"],
    "放量突破": ["breakout_60d", "volume_breakout_20d"],
    "超卖": ["rsi_14d", "reversal_5d"],
}


CATEGORY_TERM_MAP: dict[str, str] = {
    "动量因子": "momentum",
    "动量类因子": "momentum",
    "趋势因子": "trend",
    "趋势类因子": "trend",
    "量价因子": "volume_price",
    "量价类因子": "volume_price",
    "反转因子": "reversal",
    "反转类因子": "reversal",
    "风险因子": "risk",
    "风险类因子": "risk",
    "估值因子": "valuation",
    "估值类因子": "valuation",
    "质量因子": "quality",
    "质量类因子": "quality",
    "成长因子": "growth",
    "成长类因子": "growth",
}


TARGET_HORIZON_PATTERNS: dict[str, int] = {
    "下一日": 1,
    "次日": 1,
    "明天": 1,
    "未来1日": 1,
    "未来3日": 3,
    "未来5日": 5,
    "未来10日": 10,
    "未来20日": 20,
    "5日后": 5,
    "10日后": 10,
    "20日后": 20,
}


AMBIGUOUS_TERM_MAP: dict[str, list[str]] = {
    "强弱指标": ["RSI", "相对强度", "动量", "趋势强度"],
    "强弱": ["RSI", "相对强度", "动量", "趋势强度"],
    "趋势指标": ["trend_strength", "ma_gap_20d", "breakout_60d"],
    "动量指标": ["momentum_5d", "momentum_20d", "momentum_60d"],
}


EXPRESSION_KB: list[ExpressionEntry] = [
    ExpressionEntry(
        id="today_up",
        phrase="今日上涨",
        canonical_name="return_1d_positive",
        expression_type="condition_expression",
        category="price_action",
        meaning="当日收盘价相对前一交易日上涨。",
        synonyms=["今天上涨", "当日上涨", "收涨"],
        required_columns=["close"],
        derived_columns=["return_1d"],
        formula="return_1d > 0",
        calculation_hint="return_1d = close / lag(close, 1) - 1",
        operator=">",
        threshold=0.0,
        threshold_type="fixed",
        data_dependency="ohlcv",
        time_direction="current",
        can_be_condition=True,
        can_be_factor=False,
        can_be_target=False,
        leakage_risk=False,
        route_to=["condition_research", "mixed_research"],
        ambiguity_level="low",
        fallback_policy="use_return_1d",
        example_queries=["今日上涨", "今天是不是涨了"],
        related_expressions=["今日下跌", "缩量上涨", "放量上涨"],
        negative_cases=["开盘上涨但收盘下跌不算今日上涨"],
        route_intent=["condition"],
        interpretation={
            "positive": "价格当日走强。",
            "negative": "价格当日走弱。",
        },
    ),
    ExpressionEntry(
        id="today_down",
        phrase="今日下跌",
        canonical_name="return_1d_negative",
        expression_type="condition_expression",
        category="price_action",
        meaning="当日收盘价相对前一交易日下跌。",
        synonyms=["今天下跌", "当日下跌", "收跌"],
        required_columns=["close"],
        derived_columns=["return_1d"],
        formula="return_1d < 0",
        calculation_hint="return_1d = close / lag(close, 1) - 1",
        operator="<",
        threshold=0.0,
        threshold_type="fixed",
        data_dependency="ohlcv",
        time_direction="current",
        can_be_condition=True,
        can_be_factor=False,
        can_be_target=False,
        leakage_risk=False,
        route_to=["condition_research", "mixed_research"],
        ambiguity_level="low",
        fallback_policy="use_return_1d",
        example_queries=["今日下跌", "今天是不是跌了"],
        related_expressions=["今日上涨", "缩量下跌"],
        route_intent=["condition"],
        interpretation={
            "positive": "价格当日走弱。",
            "negative": "价格当日走强。",
        },
    ),
        ExpressionEntry(
            id="amount_expansion",
            phrase="成交额放大",
            canonical_name="amount_ratio_expansion",
            expression_type="condition_expression",
        category="volume",
        meaning="当日成交额相对近期均值放大。",
        synonyms=["放量", "成交额明显放大", "资金放大"],
        required_columns=["amount"],
        derived_columns=["amount_ratio_20d"],
        formula="amount_ratio_20d > 1",
        calculation_hint="amount_ratio_20d = amount / ma(amount, 20)",
        default_window=20,
        optional_windows=[5, 10, 20, 60],
        operator=">",
        threshold=1.0,
        threshold_type="moving_average_ratio",
        data_dependency="ohlcv",
        time_direction="current",
        can_be_condition=True,
        can_be_factor=True,
        can_be_target=False,
        leakage_risk=False,
        route_to=["condition_research", "factor_research", "mixed_research"],
        ambiguity_level="medium",
        fallback_policy="default_ratio_20d",
        example_queries=["成交额放大", "今天是不是放量了"],
        related_expressions=["成交量放大", "缩量", "放量上涨", "高位放量滞涨"],
        route_intent=["condition", "factor"],
        interpretation={
            "positive": "市场参与度增强，可能配合趋势确认。",
            "negative": "如果价格不跟随，可能是高位换手。",
        },
        ),
        ExpressionEntry(
            id="amount_increase",
            phrase="成交额上升",
            canonical_name="amount_ratio_expansion",
            expression_type="condition_expression",
            layer="expression_template",
            category="volume",
            meaning="当日成交额相对近期均值上升。",
            synonyms=["成交额增加", "成交额升高", "成交额抬升"],
            required_columns=["amount"],
            derived_columns=["amount_ratio_20d"],
            formula="amount_ratio_20d > 1",
            calculation_hint="和成交额放大同义，适合作为追问追加条件。",
            default_window=20,
            optional_windows=[5, 10, 20, 60],
            operator=">",
            threshold=1.0,
            threshold_type="moving_average_ratio",
            data_dependency="ohlcv",
            time_direction="current",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research", "mixed_research"],
            route_intent=["condition", "factor"],
            example_queries=["成交额上升", "加上成交额上升"],
            related_expressions=["成交额放大", "量价分"],
            correlated_with=["amount_ratio_20d"],
        ),
        ExpressionEntry(
            id="volume_expansion",
            phrase="成交量放大",
            canonical_name="volume_ratio_expansion",
            expression_type="condition_expression",
        category="volume",
        meaning="当日成交量相对近期均值放大。",
        synonyms=["量能放大", "量放大", "放量"],
        required_columns=["volume"],
        derived_columns=["volume_ratio_20d"],
        formula="volume_ratio_20d > 1",
        calculation_hint="volume_ratio_20d = volume / ma(volume, 20)",
        default_window=20,
        optional_windows=[5, 10, 20, 60],
        operator=">",
        threshold=1.0,
        threshold_type="moving_average_ratio",
        data_dependency="ohlcv",
        time_direction="current",
        can_be_condition=True,
        can_be_factor=True,
        can_be_target=False,
        leakage_risk=False,
        route_to=["condition_research", "factor_research", "mixed_research"],
        ambiguity_level="medium",
        fallback_policy="default_ratio_20d",
        example_queries=["成交量放大", "量能是不是放大了"],
        related_expressions=["成交额放大", "缩量"],
        route_intent=["condition", "factor"],
        ),
        ExpressionEntry(
            id="volume_increase",
            phrase="成交量上升",
            canonical_name="volume_ratio_expansion",
            expression_type="condition_expression",
            layer="expression_template",
            category="volume",
            meaning="当日成交量相对近期均值上升。",
            synonyms=["成交量增加", "成交量升高", "量能上升"],
            required_columns=["volume"],
            derived_columns=["volume_ratio_20d"],
            formula="volume_ratio_20d > 1",
            calculation_hint="和成交量放大同义，适合作为追问追加条件。",
            default_window=20,
            optional_windows=[5, 10, 20, 60],
            operator=">",
            threshold=1.0,
            threshold_type="moving_average_ratio",
            data_dependency="ohlcv",
            time_direction="current",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research", "mixed_research"],
            route_intent=["condition", "factor"],
            example_queries=["成交量上升", "加上成交量上升"],
            related_expressions=["成交量放大", "量价分"],
            correlated_with=["volume_ratio_20d"],
        ),
        ExpressionEntry(
            id="ma20_above",
            phrase="站上20日线",
            canonical_name="close_above_ma20",
            expression_type="condition_expression",
            layer="expression_template",
            category="trend",
            meaning="收盘价位于 20 日均线之上。",
            synonyms=["站上MA20", "突破20日均线", "20日线上方"],
            required_columns=["close"],
            derived_columns=["ma_gap_20d"],
            formula="close > ma(close, 20)",
            calculation_hint="常用于趋势确认和回调结束判断。",
            default_window=20,
            operator=">",
            threshold=0.0,
            threshold_type="moving_average_gap",
            data_dependency="ohlcv",
            time_direction="current",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["站上20日线", "加上站上20日线"],
            related_expressions=["趋势走强", "ma_gap_20d"],
            correlated_with=["ma_gap_20d"],
        ),
        ExpressionEntry(
            id="volume_shrink",
            phrase="缩量",
            canonical_name="volume_contraction",
            expression_type="condition_expression",
        category="volume",
        meaning="当日成交额或成交量低于近期均值。",
        synonyms=["缩量下跌", "缩量上涨", "无量"],
        required_columns=["amount"],
        derived_columns=["amount_ratio_20d"],
        formula="amount_ratio_20d < 1",
        calculation_hint="amount_ratio_20d = amount / ma(amount, 20)",
        default_window=20,
        optional_windows=[5, 10, 20, 60],
        operator="<",
        threshold=1.0,
        threshold_type="moving_average_ratio",
        data_dependency="ohlcv",
        time_direction="current",
        can_be_condition=True,
        can_be_factor=True,
        can_be_target=False,
        leakage_risk=False,
        route_to=["condition_research", "factor_research", "mixed_research"],
        ambiguity_level="medium",
        fallback_policy="default_ratio_20d",
        example_queries=["缩量", "今天是不是缩量"],
        related_expressions=["成交额放大", "缩量上涨", "缩量下跌"],
        route_intent=["condition", "factor"],
    ),
    ExpressionEntry(
        id="turnover_less_5",
        phrase="换手率 < 5",
        canonical_name="turnover_below_5",
        expression_type="condition_expression",
        category="liquidity",
        meaning="当日换手率低于 5%。",
        synonyms=["换手率小于5", "换手率低于5", "低换手"],
        required_columns=["turnover"],
        derived_columns=["turnover"],
        formula="turnover < 5",
        calculation_hint="turnover 直接来自平台字段或成分数据",
        operator="<",
        threshold=5.0,
        threshold_type="fixed",
        data_dependency="platform_field",
        time_direction="current",
        can_be_condition=True,
        can_be_factor=False,
        can_be_target=False,
        leakage_risk=False,
        route_to=["condition_research", "mixed_research"],
        ambiguity_level="low",
        fallback_policy="use_turnover",
        example_queries=["换手率 < 5", "低换手是不是更稳"],
        related_expressions=["换手率过高", "低流动性"],
        route_intent=["condition"],
    ),
    ExpressionEntry(
        id="quant_amount_ratio_gt_1",
        phrase="量比 > 1",
        canonical_name="intraday_volume_ratio_gt_1",
        expression_type="condition_expression",
        category="volume",
        meaning="当日成交量相对近期均值大于 1。",
        synonyms=["量比大于1", "量比超过1", "放量"],
        required_columns=["volume"],
        derived_columns=["volume_ratio_5d", "volume_ratio_20d"],
        formula="volume_ratio_intraday > 1",
        calculation_hint="量比可以用当日成交量 / 近期均量近似",
        default_window=5,
        optional_windows=[5, 10, 20],
        operator=">",
        threshold=1.0,
        threshold_type="moving_average_ratio",
        data_dependency="ohlcv",
        time_direction="current",
        can_be_condition=True,
        can_be_factor=True,
        can_be_target=False,
        leakage_risk=False,
        route_to=["condition_research", "factor_research", "mixed_research"],
        ambiguity_level="medium",
        fallback_policy="approx_intraday_ratio",
        example_queries=["量比 > 1", "量比大于1是不是放量"],
        related_expressions=["成交量放大", "成交额放大"],
        route_intent=["condition", "factor"],
    ),
    ExpressionEntry(
        id="future_1d_up",
        phrase="未来1日上涨",
        canonical_name="future_return_1d_positive",
        expression_type="target_expression",
        category="target",
        meaning="下一交易日收益率为正。",
        synonyms=["次日上涨", "明天上涨", "下日上涨"],
        required_columns=["close"],
        derived_columns=["future_return_1d"],
        formula="future_return_1d > 0",
        calculation_hint="future_return_1d = lead(close,1)/close - 1",
        operator=">",
        threshold=0.0,
        threshold_type="fixed",
        data_dependency="ohlcv",
        time_direction="future",
        can_be_condition=False,
        can_be_factor=False,
        can_be_target=True,
        leakage_risk=True,
        route_to=["condition_research", "targeting"],
        ambiguity_level="low",
        fallback_policy="use_future_return_1d",
        example_queries=["未来1日上涨", "明天会上涨吗"],
        related_expressions=["未来5日收益", "次日收益"],
        route_intent=["target", "metric"],
    ),
    ExpressionEntry(
        id="future_5d_return",
        phrase="未来5日收益",
        canonical_name="future_return_5d",
        expression_type="target_expression",
        category="target",
        meaning="未来5个交易日的收益率。",
        synonyms=["未来5天收益", "未来五日收益", "5日后收益"],
        required_columns=["close"],
        derived_columns=["future_return_5d"],
        formula="future_return_5d = lead(close,5)/close - 1",
        calculation_hint="future_return_5d = lead(close,5) / close - 1",
        default_window=5,
        optional_windows=[1, 5, 20],
        operator=">",
        threshold=0.0,
        threshold_type="future_return",
        data_dependency="ohlcv",
        time_direction="future",
        can_be_condition=False,
        can_be_factor=False,
        can_be_target=True,
        leakage_risk=True,
        route_to=["condition_research", "factor_research", "metric_analysis"],
        ambiguity_level="low",
        fallback_policy="use_future_return_5d",
        example_queries=["未来5日收益", "5天后收益怎么样"],
        related_expressions=["未来1日上涨", "未来20日收益"],
        route_intent=["target", "metric"],
    ),
    ExpressionEntry(
        id="shrink_up",
        phrase="缩量上涨",
        canonical_name="shrink_volume_up",
        expression_type="condition_expression",
        category="volume_price_combo",
        meaning="价格上涨且成交额/成交量偏低，表示上涨未明显放量配合。",
        synonyms=["无量上涨", "上涨没量", "缩量涨"],
        required_columns=["close", "volume", "amount"],
        derived_columns=["return_1d", "amount_ratio_20d", "volume_ratio_20d"],
        formula="return_1d > 0 and amount_ratio_20d < 1",
        calculation_hint="return_1d = close / lag(close,1) - 1; amount_ratio_20d = amount / ma(amount,20)",
        default_window=20,
        optional_windows=[5, 10, 20, 60],
        operator="compound",
        threshold={"return_1d": 0.0, "amount_ratio_20d": 1.0},
        threshold_type="compound_rule",
        data_dependency="ohlcv",
        time_direction="current",
        can_be_condition=True,
        can_be_factor=True,
        can_be_target=False,
        leakage_risk=False,
        route_to=["condition_research", "factor_research", "mixed_research"],
        ambiguity_level="medium",
        fallback_policy="compound_rule_template",
        example_queries=["缩量上涨", "上涨但是没量", "无量上涨是不是弱"],
        related_expressions=["放量上涨", "缩量下跌", "量价背离"],
        route_intent=["condition", "factor"],
    ),
    ExpressionEntry(
        id="volume_breakout",
        phrase="放量突破",
        canonical_name="volume_breakout",
        expression_type="condition_expression",
        category="trend_volume_combo",
        meaning="价格突破近期区间，同时成交额/成交量放大。",
        synonyms=["突破放量", "放量上破"],
        required_columns=["close", "high", "volume", "amount"],
        derived_columns=["return_1d", "amount_ratio_20d", "volume_ratio_20d"],
        formula="close > hhv(close,20) and amount_ratio_20d > 1",
        calculation_hint="close 与近20日高点比较，并结合成交额均值倍数判断",
        default_window=20,
        optional_windows=[5, 10, 20, 60],
        operator="compound",
        threshold={"breakout": True, "amount_ratio_20d": 1.0},
        threshold_type="compound_rule",
        data_dependency="ohlcv",
        time_direction="current",
        can_be_condition=True,
        can_be_factor=True,
        can_be_target=False,
        leakage_risk=False,
        route_to=["condition_research", "factor_research", "mixed_research"],
        ambiguity_level="medium",
        fallback_policy="compound_rule_template",
        example_queries=["放量突破", "突破放量后会不会继续涨"],
        related_expressions=["缩量上涨", "高位放量滞涨"],
        route_intent=["condition", "factor"],
    ),
    ExpressionEntry(
        id="high_volume_flat",
        phrase="高位放量滞涨",
        canonical_name="high_volume_no_progress",
        expression_type="condition_expression",
        category="risk_combo",
        meaning="位于近期高位附近，但成交额放大且价格涨幅不明显，偏风险信号。",
        synonyms=["高位爆量不涨", "放量不涨", "放量滞涨"],
        required_columns=["close", "volume", "amount"],
        derived_columns=["return_1d", "amount_ratio_20d", "new_high_distance_60d"],
        formula="amount_ratio_20d > 1 and abs(return_1d) < threshold",
        calculation_hint="在高位放量但价格没有继续推进时，可能意味着筹码交换剧烈。",
        default_window=20,
        optional_windows=[5, 10, 20, 60],
        operator="compound",
        threshold={"amount_ratio_20d": 1.0, "abs_return_1d": 0.01},
        threshold_type="compound_rule",
        data_dependency="ohlcv",
        time_direction="current",
        can_be_condition=True,
        can_be_factor=True,
        can_be_target=False,
        leakage_risk=False,
        route_to=["condition_research", "factor_research", "mixed_research"],
        ambiguity_level="medium",
        fallback_policy="compound_rule_template",
        example_queries=["高位放量滞涨", "放量不涨是不是危险"],
        related_expressions=["放量突破", "缩量上涨"],
        route_intent=["condition", "factor"],
    ),
]

EXPRESSION_KB.extend(
    [
        # 原始数据层
        ExpressionEntry(
            id="raw_ohlcv",
            phrase="OHLCV",
            canonical_name="ohlcv_raw_fields",
            expression_type="intent_expression",
            layer="raw_data",
            category="market_data",
            meaning="开盘价、最高价、最低价、收盘价、成交量、成交额等基础行情字段。",
            synonyms=["开高低收", "量价基础数据", "行情字段"],
            required_columns=["open", "high", "low", "close", "volume", "amount"],
            formula="open/high/low/close/volume/amount",
            calculation_hint="这是最基础的数据层，用于所有后续因子和条件计算。",
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            can_be_target=False,
            route_to=["factor_research", "data_probe"],
            route_intent=["data"],
            example_queries=["我有哪些原始数据", "OHLCV字段有哪些"],
        ),
        ExpressionEntry(
            id="raw_turnover",
            phrase="换手率",
            canonical_name="turnover_rate",
            expression_type="intent_expression",
            layer="raw_data",
            category="market_data",
            meaning="标的当日成交量与流通盘的比例，反映筹码交换活跃程度。",
            synonyms=["换手", "换手比例"],
            required_columns=["turnover"],
            formula="turnover",
            calculation_hint="通常直接来自平台字段或成分数据。",
            data_dependency="platform_field",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["换手率", "低换手"],
        ),
        ExpressionEntry(
            id="raw_index_return",
            phrase="指数涨跌",
            canonical_name="index_return",
            expression_type="intent_expression",
            layer="raw_data",
            category="market_data",
            meaning="基准指数或行业指数的当日涨跌，用于判断市场环境。",
            synonyms=["大盘涨跌", "指数涨跌幅", "市场涨跌"],
            required_columns=["index_close"],
            formula="index_return_1d",
            calculation_hint="可用指数收盘价的日收益表示。",
            data_dependency="index_data",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research", "mixed_research"],
            route_intent=["factor"],
            example_queries=["指数涨跌", "大盘今天强不强"],
        ),
        ExpressionEntry(
            id="raw_nav",
            phrase="净值",
            canonical_name="nav_fields",
            expression_type="intent_expression",
            layer="raw_data",
            category="etf_data",
            meaning="ETF 净值相关字段，例如单位净值、累计净值、净值增长率。",
            synonyms=["基金净值", "单位净值", "累计净值"],
            required_columns=["unit_nav", "accum_nav"],
            formula="unit_nav / accum_nav",
            calculation_hint="当平台提供 NAV 字段时可直接使用。",
            data_dependency="nav",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            example_queries=["净值", "单位净值"],
        ),
        ExpressionEntry(
            id="raw_fund_flow",
            phrase="资金流",
            canonical_name="fund_flow",
            expression_type="intent_expression",
            layer="raw_data",
            category="capital_flow",
            meaning="主力净流入、北向资金、ETF 申赎、资金拥挤度等资金流字段。",
            synonyms=["主力资金流向", "北向资金", "资金净流入"],
            required_columns=["fund_flow"],
            formula="fund_flow",
            calculation_hint="这类字段通常来自平台专门的资金流数据，不等同于 OHLCV。",
            data_dependency="platform_field",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research", "mixed_research"],
            route_intent=["factor"],
            example_queries=["资金流", "北向资金流入"],
        ),
        ExpressionEntry(
            id="raw_financial",
            phrase="财务",
            canonical_name="financial_data",
            expression_type="intent_expression",
            layer="raw_data",
            category="fundamental",
            meaning="估值、盈利、成长、质量等基本面原始字段。",
            synonyms=["财务数据", "估值数据", "基本面数据"],
            required_columns=["pe_ttm", "pb", "roe"],
            formula="pe/pb/roe/growth",
            calculation_hint="用于估值、质量、成长类因子。",
            data_dependency="fundamental_data",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            example_queries=["财务数据", "估值因子"],
        ),

        # 同花顺原生指标层
        ExpressionEntry(
            id="native_ma",
            phrase="MA",
            canonical_name="moving_average",
            expression_type="intent_expression",
            layer="native_indicator",
            category="trend_indicator",
            meaning="移动平均线，用于观察均线方向和价格相对均线的位置。",
            synonyms=["均线", "MA5", "MA20", "MA60"],
            required_columns=["close"],
            formula="MA(close, N)",
            calculation_hint="同花顺常用指标之一。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["MA向上", "均线多头排列"],
        ),
        ExpressionEntry(
            id="native_macd",
            phrase="MACD",
            canonical_name="macd_indicator",
            expression_type="intent_expression",
            layer="native_indicator",
            category="trend_indicator",
            meaning="指数平滑异同移动平均，用于判断趋势转强转弱。",
            synonyms=["DIF", "DEA", "MACD柱", "macd"],
            required_columns=["close"],
            formula="MACD(close, fast, slow, signal)",
            calculation_hint="适合趋势判断和金叉死叉识别。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["MACD金叉", "MACD柱翻红"],
        ),
        ExpressionEntry(
            id="native_kdj",
            phrase="KDJ",
            canonical_name="kdj_indicator",
            expression_type="intent_expression",
            layer="native_indicator",
            category="momentum_indicator",
            meaning="随机指标，用于识别超买超卖和短线拐点。",
            synonyms=["K线", "D线", "J线", "KDJ金叉", "KDJ死叉"],
            required_columns=["high", "low", "close"],
            formula="KDJ(high, low, close, N)",
            calculation_hint="常用于超买超卖和反转场景。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["KDJ超卖", "KDJ金叉"],
        ),
        ExpressionEntry(
            id="native_rsi",
            phrase="RSI",
            canonical_name="rsi_indicator",
            expression_type="intent_expression",
            layer="native_indicator",
            category="momentum_indicator",
            meaning="相对强弱指数，用于衡量涨跌力度和超买超卖程度。",
            synonyms=["RSI6", "RSI12", "RSI24"],
            required_columns=["close"],
            formula="RSI(close, N)",
            calculation_hint="可用于动量和反转分析。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["RSI超买", "RSI偏弱"],
        ),
        ExpressionEntry(
            id="native_boll",
            phrase="BOLL",
            canonical_name="boll_indicator",
            expression_type="intent_expression",
            layer="native_indicator",
            category="trend_reversal_indicator",
            meaning="布林带，用于识别通道、波动收敛和突破。",
            synonyms=["布林带", "布林", "上轨", "中轨", "下轨"],
            required_columns=["close"],
            formula="BOLL(close, N, k)",
            calculation_hint="适合配合突破、回撤和过热判断。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["BOLL下轨反弹", "突破上轨"],
        ),
        ExpressionEntry(
            id="native_bbi",
            phrase="BBI",
            canonical_name="bbi_indicator",
            expression_type="intent_expression",
            layer="native_indicator",
            category="trend_indicator",
            meaning="多空指标，通常由多周期均线组合得到，用于观察趋势方向。",
            synonyms=["bbi", "多空指标", "多空均线"],
            required_columns=["close"],
            derived_columns=["bbi"],
            formula="BBI(close, 3, 6, 12, 24)",
            calculation_hint="当前知识库能识别 BBI，但执行层尚未接入统一计算入口。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["factor_research", "manual_review"],
            route_intent=["factor"],
            example_queries=["BBI", "多空指标", "BBI走强"],
            knowledge_status="known",
            implementation_status="not_implemented",
            implementation_key="bbi",
            selection_group="trend",
            selection_priority=80,
        ),
        ExpressionEntry(
            id="native_obv",
            phrase="OBV",
            canonical_name="obv_indicator",
            expression_type="intent_expression",
            layer="native_indicator",
            category="volume_indicator",
            meaning="能量潮指标，用于观察量能与价格是否同步。",
            synonyms=["能量潮", "OBV上涨", "OBV背离"],
            required_columns=["close", "volume"],
            formula="OBV(close, volume)",
            calculation_hint="常与背离、趋势确认一起使用。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["OBV上涨", "OBV背离"],
        ),
        ExpressionEntry(
            id="native_bias",
            phrase="BIAS",
            canonical_name="bias_indicator",
            expression_type="intent_expression",
            layer="native_indicator",
            category="mean_reversion_indicator",
            meaning="乖离率，用于判断价格偏离均线程度。",
            synonyms=["乖离率", "BIAS5", "BIAS20"],
            required_columns=["close"],
            formula="BIAS(close, N)",
            calculation_hint="偏离过大常对应超买或超卖。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["BIAS过高", "乖离过大"],
        ),
        ExpressionEntry(
            id="native_dmi",
            phrase="DMI",
            canonical_name="dmi_indicator",
            expression_type="intent_expression",
            layer="native_indicator",
            category="trend_indicator",
            meaning="方向运动指标，用于衡量趋势方向与强度。",
            synonyms=["ADX", "PDI", "MDI"],
            required_columns=["high", "low", "close"],
            formula="DMI(high, low, close, N)",
            calculation_hint="适合趋势是否有效的判断。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["DMI走强", "ADX抬升"],
        ),
        ExpressionEntry(
            id="native_sar",
            phrase="SAR",
            canonical_name="parabolic_sar",
            expression_type="intent_expression",
            layer="native_indicator",
            category="trend_indicator",
            meaning="抛物线转向指标，用于判断趋势翻转。",
            synonyms=["抛物线SAR", "SAR翻多", "SAR翻空"],
            required_columns=["high", "low"],
            formula="SAR(high, low, N)",
            calculation_hint="常用于趋势转折观察。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["SAR翻多", "SAR转弱"],
        ),
        ExpressionEntry(
            id="native_vr",
            phrase="VR",
            canonical_name="volume_ratio_indicator",
            expression_type="intent_expression",
            layer="native_indicator",
            category="volume_indicator",
            meaning="成交量比率指标，用于判断多空力量与量能结构。",
            synonyms=["量比指标", "VR指标"],
            required_columns=["close", "volume"],
            formula="VR(close, volume)",
            calculation_hint="可辅助判断放量或缩量是否有意义。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["VR走强", "量比偏高"],
        ),

        # 加工因子层
        ExpressionEntry(
            id="amount_ratio_20d",
            phrase="amount_ratio_20d",
            canonical_name="amount_ratio_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="volume",
            meaning="当日成交额 / 20日均成交额。",
            synonyms=["成交额比20日均值", "AMO/MA20", "成交额放大因子"],
            required_columns=["amount"],
            derived_columns=["amount_ratio_20d"],
            formula="amount / ma(amount, 20)",
            calculation_hint="用于判断资金是否放大。",
            default_window=20,
            optional_windows=[5, 10, 20, 60],
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research", "mixed_research"],
            route_intent=["condition", "factor"],
            related_expressions=["volume_ratio_20d", "成交额放大", "缩量"],
            correlated_with=["volume_ratio_20d"],
            example_queries=["成交额放大", "AMO放大"],
        ),
        ExpressionEntry(
            id="volume_ratio_20d",
            phrase="volume_ratio_20d",
            canonical_name="volume_ratio_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="volume",
            meaning="当日成交量 / 20日均成交量。",
            synonyms=["成交量比20日均值", "VOL/MA20"],
            required_columns=["volume"],
            derived_columns=["volume_ratio_20d"],
            formula="volume / ma(volume, 20)",
            calculation_hint="用于确认放量或缩量。",
            default_window=20,
            optional_windows=[5, 10, 20, 60],
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research", "mixed_research"],
            route_intent=["condition", "factor"],
            related_expressions=["amount_ratio_20d", "成交量放大", "缩量"],
            correlated_with=["amount_ratio_20d"],
            example_queries=["成交量放大", "缩量"],
        ),
        ExpressionEntry(
            id="momentum_20d",
            phrase="momentum_20d",
            canonical_name="momentum_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="momentum",
            meaning="20日价格涨幅。",
            synonyms=["20日动量", "20日涨幅", "ROC20", "C/REF(C,20)-1"],
            required_columns=["close"],
            derived_columns=["momentum_20d"],
            formula="close / lag(close, 20) - 1",
            calculation_hint="动量最常见的基础版本。",
            default_window=20,
            optional_windows=[5, 10, 20, 60, 120],
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research", "mixed_research"],
            route_intent=["factor"],
            related_expressions=["roc_20d", "relative_strength_20d"],
            correlated_with=["roc_20d", "relative_strength_20d"],
            example_queries=["20日涨幅", "动量20日"],
        ),
        ExpressionEntry(
            id="roc_20d",
            phrase="roc_20d",
            canonical_name="roc_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="momentum",
            meaning="20日变动率，和 20 日涨幅本质接近。",
            synonyms=["ROC20", "20日ROC"],
            required_columns=["close"],
            derived_columns=["roc_20d"],
            formula="close / lag(close, 20) - 1",
            calculation_hint="与 momentum_20d 重叠度很高，二者不要同时重复加权。",
            default_window=20,
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            related_expressions=["momentum_20d"],
            correlated_with=["momentum_20d"],
            example_queries=["ROC20", "20日ROC"],
        ),
        ExpressionEntry(
            id="relative_strength_20d",
            phrase="relative_strength_20d",
            canonical_name="relative_strength_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="momentum",
            meaning="标的20日涨幅相对基准指数的超额强弱。",
            synonyms=["相对强弱20日", "RS20", "20日超额收益"],
            required_columns=["close"],
            derived_columns=["relative_strength_20d"],
            formula="momentum_20d - benchmark_momentum_20d",
            calculation_hint="如果用户说‘比大盘强’，优先映射这个表达。",
            default_window=20,
            data_dependency="index_data",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research", "mixed_research"],
            route_intent=["factor"],
            related_expressions=["momentum_20d", "momentum_rank_20d"],
            correlated_with=["momentum_20d"],
            example_queries=["相对沪深300更强", "行业ETF更强"],
        ),
        ExpressionEntry(
            id="ma_gap_20d",
            phrase="ma_gap_20d",
            canonical_name="ma_gap_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="trend",
            meaning="收盘价相对20日均线的偏离程度。",
            synonyms=["MA20乖离", "C/MA20-1", "20日均线乖离"],
            required_columns=["close"],
            derived_columns=["ma_gap_20d"],
            formula="close / ma(close, 20) - 1",
            calculation_hint="趋势与均值回归都可用。",
            default_window=20,
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research", "mixed_research"],
            route_intent=["factor"],
            related_expressions=["bias_20d", "trend_persistence_20d"],
            correlated_with=["bias_20d"],
            example_queries=["MA20上方多少", "20日均线乖离"],
        ),
        ExpressionEntry(
            id="ma_gap_60d",
            phrase="ma_gap_60d",
            canonical_name="ma_gap_60d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="trend",
            meaning="收盘价相对60日均线的偏离程度。",
            synonyms=["MA60乖离", "C/MA60-1", "60日均线乖离"],
            required_columns=["close"],
            derived_columns=["ma_gap_60d"],
            formula="close / ma(close, 60) - 1",
            calculation_hint="常用于中期趋势和位置判断。",
            default_window=60,
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research", "mixed_research"],
            route_intent=["factor"],
            related_expressions=["bias_60d", "new_high_distance_60d"],
            correlated_with=["bias_60d"],
            example_queries=["MA60上方多少", "60日均线乖离"],
        ),
        ExpressionEntry(
            id="obv_divergence_20d",
            phrase="obv_divergence_20d",
            canonical_name="obv_divergence_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="volume_trend",
            meaning="价格与 OBV 的同步程度或背离程度。",
            synonyms=["OBV背离", "能量潮背离", "量价背离"],
            required_columns=["close", "volume"],
            derived_columns=["obv_divergence_20d"],
            formula="corr(price_trend, obv_trend) or price_trend - obv_trend",
            calculation_hint="用于识别价格与量能是否同向。",
            default_window=20,
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            related_expressions=["price_volume_corr_20d", "OBV"],
            correlated_with=["price_volume_corr_20d", "amount_ratio_20d"],
            example_queries=["OBV背离", "量价背离"],
        ),
        ExpressionEntry(
            id="price_volume_corr_20d",
            phrase="price_volume_corr_20d",
            canonical_name="price_volume_corr_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="volume_trend",
            meaning="价格收益与成交量/成交额变化的滚动相关性。",
            synonyms=["量价相关性", "价格成交量相关", "量价同步"],
            required_columns=["close", "volume", "amount"],
            derived_columns=["price_volume_corr_20d"],
            formula="corr(return_1d, amount_change_1d)",
            calculation_hint="用于量价同向或背离的统计检验。",
            default_window=20,
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            related_expressions=["obv_divergence_20d"],
            correlated_with=["obv_divergence_20d"],
            example_queries=["量价背离", "量价同步性"],
        ),
        ExpressionEntry(
            id="trend_persistence_20d",
            phrase="trend_persistence_20d",
            canonical_name="trend_persistence_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="trend",
            meaning="过去20日中价格位于关键均线上方或收阳的持续性。",
            synonyms=["趋势持续", "走强持续性", "持续站上MA20"],
            required_columns=["close"],
            derived_columns=["trend_persistence_20d"],
            formula="count(close > ma(close,20)) / 20",
            calculation_hint="用于区分持续走强与一次性冲高。",
            default_window=20,
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            related_expressions=["momentum_consistency_20d", "ma_gap_20d"],
            correlated_with=["momentum_consistency_20d"],
            example_queries=["趋势持续性", "是否一直站稳均线"],
        ),
        ExpressionEntry(
            id="momentum_consistency_20d",
            phrase="momentum_consistency_20d",
            canonical_name="momentum_consistency_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="momentum",
            meaning="过去20日上涨天数占比。",
            synonyms=["阳线占比20日", "上涨天数占比", "连续走强"],
            required_columns=["close"],
            derived_columns=["momentum_consistency_20d"],
            formula="count(return_1d > 0) / 20",
            calculation_hint="用于衡量动量是否稳定。",
            default_window=20,
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            related_expressions=["trend_persistence_20d"],
            correlated_with=["trend_persistence_20d"],
            example_queries=["上涨天数占比", "动量是否稳定"],
        ),
        ExpressionEntry(
            id="boll_lower_rebound",
            phrase="boll_lower_rebound",
            canonical_name="boll_lower_rebound",
            expression_type="condition_expression",
            layer="processed_factor",
            category="reversal",
            meaning="价格触及或跌破布林下轨后回升。",
            synonyms=["BOLL下轨反弹", "下轨反弹", "跌破下轨回升"],
            required_columns=["close"],
            derived_columns=["boll_lower_rebound"],
            formula="close <= boll_lower and close_recover",
            calculation_hint="适合反转研究，但要结合趋势位置。",
            default_window=20,
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            related_expressions=["rsi_oversold_20d", "long_lower_shadow_reversal"],
            correlated_with=["rsi_oversold_20d"],
            example_queries=["BOLL下轨反弹", "跌破布林下轨后回升"],
        ),
        ExpressionEntry(
            id="rsi_overbought_20d",
            phrase="rsi_overbought_20d",
            canonical_name="rsi_overbought_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="reversal_risk",
            meaning="RSI 位于超买区域。",
            synonyms=["RSI过热", "RSI超买"],
            required_columns=["close"],
            derived_columns=["rsi_overbought_20d"],
            formula="rsi_20d > 70",
            calculation_hint="常与高位风险判断配合使用。",
            default_window=20,
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            related_expressions=["overheat", "high_position"],
            example_queries=["RSI过热", "RSI超买"],
        ),
        ExpressionEntry(
            id="rsi_oversold_20d",
            phrase="rsi_oversold_20d",
            canonical_name="rsi_oversold_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="reversal",
            meaning="RSI 位于超卖区域。",
            synonyms=["RSI超卖", "RSI偏弱"],
            required_columns=["close"],
            derived_columns=["rsi_oversold_20d"],
            formula="rsi_20d < 30",
            calculation_hint="常与反弹研究和超跌修复结合。",
            default_window=20,
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            related_expressions=["boll_lower_rebound", "long_lower_shadow_reversal"],
            example_queries=["RSI超卖", "RSI过低"],
        ),
        ExpressionEntry(
            id="volatility_20d",
            phrase="volatility_20d",
            canonical_name="volatility_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="risk",
            meaning="20日收益波动率。",
            synonyms=["20日波动率", "收益波动", "风险波动"],
            required_columns=["close"],
            derived_columns=["volatility_20d"],
            formula="std(return_1d, 20)",
            calculation_hint="用于衡量风险和仓位约束。",
            default_window=20,
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            example_queries=["波动率高不高", "风险大不大"],
        ),
        ExpressionEntry(
            id="drawdown_20d",
            phrase="drawdown_20d",
            canonical_name="drawdown_20d",
            expression_type="factor_expression",
            layer="processed_factor",
            category="risk",
            meaning="20日最大回撤或区间回撤。",
            synonyms=["20日回撤", "跌幅回撤"],
            required_columns=["close"],
            derived_columns=["drawdown_20d"],
            formula="close / rolling_max(close, 20) - 1",
            calculation_hint="用于识别阶段性风险。",
            default_window=20,
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            example_queries=["最近回撤多大", "区间回撤"],
        ),
        ExpressionEntry(
            id="market_environment_score",
            phrase="市场环境分",
            canonical_name="market_environment_score",
            expression_type="factor_expression",
            layer="composite_score",
            category="environment",
            meaning="市场整体是否适合进攻或防守的综合评分。",
            synonyms=["大盘温度", "市场温度", "风险偏好分"],
            required_columns=["close"],
            derived_columns=["market_environment_score"],
            formula="index_momentum + breadth + volatility_penalty",
            calculation_hint="由指数趋势、市场广度、波动率共同合成。",
            data_dependency="index_data",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            example_queries=["市场温度", "当前环境适合进攻吗"],
        ),

        # 综合评分层
        ExpressionEntry(
            id="score_volume_price",
            phrase="量价分",
            canonical_name="volume_price_score",
            expression_type="metric_expression",
            layer="composite_score",
            category="composite_score",
            meaning="把量能活跃、放量突破、量价同步等信息合成一个量价评分。",
            synonyms=["量价综合分", "成交额评分"],
            required_columns=["amount", "volume", "close"],
            derived_columns=["volume_price_score"],
            formula="weighted_sum(amount_ratio_20d, volume_ratio_20d, obv_divergence_20d)",
            calculation_hint="适合做第一层过滤或横截面排序。",
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            can_be_target=False,
            route_to=["factor_research"],
            route_intent=["factor"],
            related_expressions=["amount_ratio_20d", "volume_ratio_20d"],
            correlated_with=["amount_ratio_20d", "volume_ratio_20d"],
            example_queries=["量价分", "量价综合评分"],
        ),
        ExpressionEntry(
            id="score_momentum",
            phrase="动量分",
            canonical_name="momentum_score",
            expression_type="metric_expression",
            layer="composite_score",
            category="composite_score",
            meaning="把阶段涨幅、相对强度、动量持续性合成一个动量评分。",
            synonyms=["动量综合分", "涨幅评分"],
            required_columns=["close"],
            derived_columns=["momentum_score"],
            formula="weighted_sum(momentum_20d, relative_strength_20d, momentum_consistency_20d)",
            calculation_hint="适合找强者恒强的 ETF。",
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            related_expressions=["momentum_20d", "relative_strength_20d"],
            correlated_with=["momentum_20d", "relative_strength_20d"],
            example_queries=["动量分", "涨幅评分"],
        ),
        ExpressionEntry(
            id="score_trend",
            phrase="趋势分",
            canonical_name="trend_score",
            expression_type="metric_expression",
            layer="composite_score",
            category="composite_score",
            meaning="把均线结构、MACD、SAR、趋势持续性等合成趋势评分。",
            synonyms=["趋势综合分", "趋势强度分"],
            required_columns=["close"],
            derived_columns=["trend_score"],
            formula="weighted_sum(ma_gap_20d, ma_gap_60d, trend_persistence_20d, macd_hist)",
            calculation_hint="适合判断是否处于可持有趋势环境。",
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            related_expressions=["ma_gap_20d", "trend_persistence_20d"],
            correlated_with=["ma_gap_20d", "trend_persistence_20d"],
            example_queries=["趋势分", "趋势强度"],
        ),
        ExpressionEntry(
            id="score_reversal",
            phrase="反转分",
            canonical_name="reversal_score",
            expression_type="metric_expression",
            layer="composite_score",
            category="composite_score",
            meaning="把超卖、下影线、BOLL 反弹、乖离修复等合成反转评分。",
            synonyms=["反弹分", "修复分"],
            required_columns=["close", "high", "low"],
            derived_columns=["reversal_score"],
            formula="weighted_sum(rsi_oversold_20d, boll_lower_rebound, long_lower_shadow_reversal)",
            calculation_hint="适合寻找超跌修复机会。",
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            related_expressions=["rsi_oversold_20d", "boll_lower_rebound"],
            correlated_with=["rsi_oversold_20d"],
            example_queries=["反转分", "超跌反弹评分"],
        ),
        ExpressionEntry(
            id="score_risk",
            phrase="风险分",
            canonical_name="risk_score",
            expression_type="metric_expression",
            layer="composite_score",
            category="composite_score",
            meaning="把波动率、回撤、过热和高位风险合成风险评分。",
            synonyms=["风险综合分", "回撤风险分"],
            required_columns=["close"],
            derived_columns=["risk_score"],
            formula="weighted_sum(volatility_20d, drawdown_20d, rsi_overbought_20d)",
            calculation_hint="分数越高代表越不适合激进追涨。",
            data_dependency="ohlcv",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            related_expressions=["volatility_20d", "drawdown_20d"],
            correlated_with=["volatility_20d", "drawdown_20d"],
            example_queries=["风险分", "波动风险"],
        ),
        ExpressionEntry(
            id="score_valuation",
            phrase="估值分",
            canonical_name="valuation_score",
            expression_type="metric_expression",
            layer="composite_score",
            category="composite_score",
            meaning="把 PE、PB、历史分位等合成估值评分。",
            synonyms=["估值综合分", "便宜程度"],
            required_columns=["pe_ttm", "pb"],
            derived_columns=["valuation_score"],
            formula="weighted_sum(industry_pe_percentile, industry_pb_percentile)",
            calculation_hint="估值越低通常分数越高。",
            data_dependency="fundamental_data",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            example_queries=["估值分", "贵不贵"],
        ),
        ExpressionEntry(
            id="score_quality",
            phrase="质量分",
            canonical_name="quality_score",
            expression_type="metric_expression",
            layer="composite_score",
            category="composite_score",
            meaning="把 ROE、盈利能力、稳定性等合成质量评分。",
            synonyms=["质量综合分", "基本面质量分"],
            required_columns=["roe"],
            derived_columns=["quality_score"],
            formula="weighted_sum(weighted_roe, profit_margin, stability)",
            calculation_hint="适合筛选基本面更扎实的行业ETF。",
            data_dependency="fundamental_data",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            example_queries=["质量分", "基本面质量"],
        ),
        ExpressionEntry(
            id="score_growth",
            phrase="成长分",
            canonical_name="growth_score",
            expression_type="metric_expression",
            layer="composite_score",
            category="composite_score",
            meaning="把营收、利润、景气度等合成成长评分。",
            synonyms=["成长综合分", "增长分"],
            required_columns=["growth"],
            derived_columns=["growth_score"],
            formula="weighted_sum(weighted_profit_growth, revenue_growth, industry_cycle)",
            calculation_hint="适合筛选高景气度行业。",
            data_dependency="fundamental_data",
            can_be_condition=False,
            can_be_factor=True,
            route_to=["factor_research"],
            route_intent=["factor"],
            example_queries=["成长分", "成长性怎么样"],
        ),

        # 模糊/修饰表达
        ExpressionEntry(
            id="modifier_obvious",
            phrase="明显",
            canonical_name="obvious_strength_modifier",
            expression_type="intent_expression",
            layer="intent_modifier",
            category="modifier",
            meaning="表示变化幅度较为清晰、统计上更强的口语化修饰词。",
            synonyms=["明显放大", "明显走强", "明显走弱"],
            calculation_hint="通常要和放量、上涨、下跌、过热等核心表达组合使用。",
            data_dependency="none",
            can_be_condition=False,
            can_be_factor=False,
            can_be_target=False,
            route_to=["mixed_research", "manual_review"],
            route_intent=["modifier"],
            ambiguity_level="high",
            example_queries=["明显放量", "明显走强"],
        ),
        ExpressionEntry(
            id="modifier_overheat",
            phrase="过热",
            canonical_name="overheat_modifier",
            expression_type="intent_expression",
            layer="intent_modifier",
            category="modifier",
            meaning="表示短期涨幅过快、风险偏高或情绪偏热。",
            synonyms=["高位过热", "短线过热", "涨太快"],
            calculation_hint="常与 RSI、乖离率、BOLL 上轨、量价放大一起使用。",
            data_dependency="none",
            can_be_condition=False,
            can_be_factor=False,
            route_to=["mixed_research", "manual_review"],
            route_intent=["modifier"],
            ambiguity_level="high",
            example_queries=["是否过热", "这个位置过热吗"],
        ),
        ExpressionEntry(
            id="modifier_near_high",
            phrase="接近新高",
            canonical_name="near_new_high_modifier",
            expression_type="intent_expression",
            layer="intent_modifier",
            category="modifier",
            meaning="表示价格距离阶段高点很近。",
            synonyms=["接近高点", "接近前高", "离新高不远"],
            calculation_hint="常映射为 new_high_distance_* 接近 0。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            ambiguity_level="medium",
            example_queries=["接近新高", "快到前高了"],
        ),
        ExpressionEntry(
            id="modifier_high_position",
            phrase="高位",
            canonical_name="high_position_modifier",
            expression_type="intent_expression",
            layer="intent_modifier",
            category="modifier",
            meaning="表示价格处在阶段高位附近，偏风险语境。",
            synonyms=["高位震荡", "高位横盘", "高位放量"],
            calculation_hint="通常要结合回撤、乖离、BOLL 上轨来判断。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            ambiguity_level="medium",
            example_queries=["高位放量", "高位是不是危险"],
        ),
        ExpressionEntry(
            id="modifier_strong_trend",
            phrase="趋势走强",
            canonical_name="strong_trend_modifier",
            expression_type="intent_expression",
            layer="intent_modifier",
            category="modifier",
            meaning="表示趋势结构持续改善，短中期趋势偏多。",
            synonyms=["走强", "趋势增强", "强趋势"],
            calculation_hint="可映射到趋势分、MA gap、MACD、ADX。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            ambiguity_level="medium",
            example_queries=["趋势走强", "明显转强"],
        ),
        # 高频口语组合模板
        ExpressionEntry(
            id="volume_up_price_up",
            phrase="放量上涨",
            canonical_name="volume_expansion_price_up",
            expression_type="condition_expression",
            layer="expression_template",
            category="volume_price_combo",
            meaning="价格上涨且成交额或成交量放大。",
            synonyms=["带量上涨", "上涨放量", "量价齐升"],
            required_columns=["close", "amount", "volume"],
            derived_columns=["return_1d", "amount_ratio_20d", "volume_ratio_20d"],
            formula="return_1d > 0 and amount_ratio_20d > 1",
            calculation_hint="优先用成交额放大确认，成交量作为辅助确认。",
            default_window=20,
            operator="compound",
            threshold={"return_1d": 0.0, "amount_ratio_20d": 1.0},
            threshold_type="compound_rule",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["放量上涨", "上涨放量后明天会涨吗"],
            related_expressions=["成交额放大", "今日上涨", "放量突破"],
            correlated_with=["amount_ratio_20d", "volume_ratio_20d"],
        ),
        ExpressionEntry(
            id="volume_up_price_down",
            phrase="放量下跌",
            canonical_name="volume_expansion_price_down",
            expression_type="condition_expression",
            layer="expression_template",
            category="risk_combo",
            meaning="价格下跌且成交额或成交量放大，通常偏风险释放。",
            synonyms=["带量下跌", "下跌放量", "放量杀跌"],
            required_columns=["close", "amount", "volume"],
            derived_columns=["return_1d", "amount_ratio_20d", "volume_ratio_20d"],
            formula="return_1d < 0 and amount_ratio_20d > 1",
            calculation_hint="可用于检验放量杀跌后的短期反弹或延续下跌概率。",
            default_window=20,
            operator="compound",
            threshold={"return_1d": 0.0, "amount_ratio_20d": 1.0},
            threshold_type="compound_rule",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["放量下跌", "放量杀跌后会反弹吗"],
            related_expressions=["今日下跌", "成交额放大"],
            correlated_with=["amount_ratio_20d", "volume_ratio_20d"],
        ),
        ExpressionEntry(
            id="shrink_down",
            phrase="缩量下跌",
            canonical_name="shrink_volume_down",
            expression_type="condition_expression",
            layer="expression_template",
            category="volume_price_combo",
            meaning="价格下跌但成交额或成交量萎缩。",
            synonyms=["无量下跌", "下跌缩量", "缩量回调"],
            required_columns=["close", "amount", "volume"],
            derived_columns=["return_1d", "amount_ratio_20d", "volume_ratio_20d"],
            formula="return_1d < 0 and amount_ratio_20d < 1",
            calculation_hint="在上升趋势中可能是健康回调，在弱趋势中可能是买盘不足。",
            default_window=20,
            operator="compound",
            threshold={"return_1d": 0.0, "amount_ratio_20d": 1.0},
            threshold_type="compound_rule",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["缩量下跌", "缩量回调后会涨吗"],
            related_expressions=["缩量", "今日下跌"],
            correlated_with=["amount_ratio_20d", "volume_ratio_20d"],
        ),
        ExpressionEntry(
            id="pullback_shrink_volume",
            phrase="缩量回调",
            canonical_name="pullback_shrink_volume",
            expression_type="condition_expression",
            layer="expression_template",
            category="volume_price_combo",
            meaning="趋势中价格回调但成交额萎缩。",
            synonyms=["回调缩量", "缩量调整"],
            required_columns=["close", "amount"],
            derived_columns=["return_1d", "amount_ratio_20d", "trend_persistence_20d"],
            formula="return_1d < 0 and amount_ratio_20d < 1 and trend_persistence_20d > 0.5",
            calculation_hint="需要同时判断短期下跌、成交额萎缩和趋势背景。",
            default_window=20,
            operator="compound",
            threshold={"return_1d": 0.0, "amount_ratio_20d": 1.0, "trend_persistence_20d": 0.5},
            threshold_type="compound_rule",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["缩量回调", "趋势中缩量回调"],
            related_expressions=["缩量下跌", "趋势走强"],
        ),
        ExpressionEntry(
            id="price_breakout",
            phrase="突破前高",
            canonical_name="price_breakout_previous_high",
            expression_type="condition_expression",
            layer="expression_template",
            category="breakout",
            meaning="价格突破近期高点或阶段前高。",
            synonyms=["突破平台", "创新高", "阶段新高", "横盘突破"],
            required_columns=["close", "high"],
            derived_columns=["new_high_breakout_20d", "new_high_distance_20d"],
            formula="close > ref(hhv(close, 20), 1)",
            calculation_hint="默认按20日阶段高点理解，也可按60日或120日扩展。",
            default_window=20,
            optional_windows=[20, 60, 120],
            operator=">",
            threshold=0.0,
            threshold_type="breakout",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["突破前高", "横盘突破后收益"],
            related_expressions=["放量突破", "接近新高"],
        ),
        ExpressionEntry(
            id="macd_golden_cross",
            phrase="MACD金叉",
            canonical_name="macd_golden_cross",
            expression_type="condition_expression",
            layer="expression_template",
            category="trend_indicator",
            meaning="MACD DIF 上穿 DEA。",
            synonyms=["macd金叉", "DIF上穿DEA"],
            required_columns=["close"],
            derived_columns=["macd_dif", "macd_dea", "macd_golden_cross"],
            formula="macd_dif > macd_dea and lag(macd_dif,1) <= lag(macd_dea,1)",
            calculation_hint="趋势转强信号，建议结合趋势分和成交额。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["MACD金叉", "MACD金叉后会涨吗"],
            related_expressions=["MACD", "趋势走强"],
        ),
        ExpressionEntry(
            id="macd_dead_cross",
            phrase="MACD死叉",
            canonical_name="macd_dead_cross",
            expression_type="condition_expression",
            layer="expression_template",
            category="trend_indicator",
            meaning="MACD DIF 下穿 DEA。",
            synonyms=["macd死叉", "DIF下穿DEA"],
            required_columns=["close"],
            derived_columns=["macd_dif", "macd_dea", "macd_dead_cross"],
            formula="macd_dif < macd_dea and lag(macd_dif,1) >= lag(macd_dea,1)",
            calculation_hint="趋势转弱信号，建议结合风险分。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["MACD死叉", "MACD死叉后风险"],
            related_expressions=["MACD", "趋势走弱"],
        ),
        ExpressionEntry(
            id="kdj_golden_cross",
            phrase="KDJ金叉",
            canonical_name="kdj_golden_cross",
            expression_type="condition_expression",
            layer="expression_template",
            category="reversal",
            meaning="KDJ K 线上穿 D 线。",
            synonyms=["kdj金叉", "K线上穿D线"],
            required_columns=["high", "low", "close"],
            derived_columns=["kdj_k", "kdj_d", "kdj_golden_cross"],
            formula="kdj_k > kdj_d and lag(kdj_k,1) <= lag(kdj_d,1)",
            calculation_hint="低位金叉更偏反转，高位金叉可能偏追涨。",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["KDJ金叉", "低位KDJ金叉"],
            related_expressions=["KDJ", "超卖"],
        ),
        ExpressionEntry(
            id="rsi_oversold",
            phrase="超卖",
            canonical_name="oversold_condition",
            expression_type="condition_expression",
            layer="expression_template",
            category="reversal",
            meaning="价格或指标进入短期超卖区域。",
            synonyms=["RSI超卖", "跌多了", "短线超跌"],
            required_columns=["close"],
            derived_columns=["rsi_oversold_20d", "reversal_5d"],
            formula="rsi_20d < 30 or momentum_5d is low percentile",
            calculation_hint="默认用 RSI 和短期跌幅分位共同判断。",
            default_window=20,
            operator="<",
            threshold=30.0,
            threshold_type="indicator_level",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["超卖后会反弹吗", "短线超跌"],
            related_expressions=["反转分", "BOLL下轨反弹"],
        ),
        ExpressionEntry(
            id="rsi_overbought",
            phrase="超买",
            canonical_name="overbought_condition",
            expression_type="condition_expression",
            layer="expression_template",
            category="risk",
            meaning="价格或指标进入短期超买区域。",
            synonyms=["RSI超买", "短线过热", "涨多了"],
            required_columns=["close"],
            derived_columns=["rsi_overbought_20d", "short_term_overheat_5d"],
            formula="rsi_20d > 70 or momentum_5d is high percentile",
            calculation_hint="默认用 RSI 和短期涨幅分位共同判断。",
            default_window=20,
            operator=">",
            threshold=70.0,
            threshold_type="indicator_level",
            data_dependency="ohlcv",
            can_be_condition=True,
            can_be_factor=True,
            route_to=["condition_research", "factor_research"],
            route_intent=["condition", "factor"],
            example_queries=["超买后会跌吗", "短线过热"],
            related_expressions=["风险分", "过热"],
        ),
    ExpressionEntry(
        id="future_20d_return",
        phrase="未来20日收益",
        canonical_name="future_return_20d",
        expression_type="target_expression",
            layer="target",
            category="target",
            meaning="未来20个交易日的收益率。",
            synonyms=["未来20天收益", "一个月后收益", "20日后收益"],
            required_columns=["close"],
        derived_columns=["future_return_20d"],
        formula="future_return_20d = lead(close,20)/close - 1",
        calculation_hint="只能作为研究标签，不能作为因子或条件。",
        default_window=20,
        operator=">",
        threshold=0.0,
        threshold_type="future_return",
            data_dependency="ohlcv",
            time_direction="future",
            can_be_target=True,
            leakage_risk=True,
            route_to=["condition_research", "factor_research", "metric_analysis"],
            route_intent=["target", "metric"],
            example_queries=["未来20日收益", "一个月后收益怎么样"],
            related_expressions=["未来5日收益", "未来1日上涨"],
        ),
        ExpressionEntry(
            id="sort_top_pct",
            phrase="选前10%",
            canonical_name="select_top_pct",
            expression_type="sort_expression",
            layer="execution_intent",
            category="ranking",
            meaning="按某个评分或因子排序后选择排名靠前的一部分标的。",
            synonyms=["Top10%", "前10%", "排名前10%", "选最强的一批"],
            formula="rank(score) >= top_pct",
            calculation_hint="默认用于因子评分或综合评分后的选 ETF 步骤。",
            operator="top_pct",
            threshold=0.1,
            threshold_type="ranking_cutoff",
            data_dependency="none",
            can_be_condition=False,
            can_be_factor=False,
            route_to=["factor_research", "backtest"],
            route_intent=["sort", "backtest"],
            example_queries=["选前10%", "按趋势分选前10%"],
        ),
        ExpressionEntry(
            id="sort_bottom_pct",
            phrase="选后10%",
            canonical_name="select_bottom_pct",
            expression_type="sort_expression",
            layer="execution_intent",
            category="ranking",
            meaning="按某个评分或因子排序后选择排名靠后的一部分标的。",
            synonyms=["Bottom10%", "后10%", "排名后10%", "选最弱的一批"],
            formula="rank(score) <= bottom_pct",
            calculation_hint="通常用于对照组、反向检验或多空研究。",
            operator="bottom_pct",
            threshold=0.1,
            threshold_type="ranking_cutoff",
            data_dependency="none",
            route_to=["factor_research", "backtest"],
            route_intent=["sort", "backtest"],
            example_queries=["选后10%", "最弱ETF表现"],
        ),
    ]
)


def match_factor_terms(query: str) -> list[str]:
    text = _normalize_text(query)
    matched: list[str] = []
    for term, factor_names in FACTOR_TERM_MAP.items():
        if _normalize_text(term) in text:
            matched.extend(factor_names)
    return list(dict.fromkeys(matched))


def match_category_terms(query: str) -> list[str]:
    text = _normalize_text(query)
    matched: list[str] = []
    for term, category in CATEGORY_TERM_MAP.items():
        if _normalize_text(term) in text:
            matched.append(category)
    return list(dict.fromkeys(matched))


def extract_target_horizon(query: str) -> int | None:
    text = _normalize_text(query)
    for term, horizon in sorted(TARGET_HORIZON_PATTERNS.items(), key=lambda item: len(item[0]), reverse=True):
        if _normalize_text(term) in text:
            return horizon
    return None


def find_ambiguous_terms(query: str) -> list[str]:
    text = _normalize_text(query)
    matched: list[str] = []
    for term, candidates in AMBIGUOUS_TERM_MAP.items():
        if _normalize_text(term) in text:
            matched.extend(candidates)
    return list(dict.fromkeys(matched))


def get_expression_kb() -> list[dict]:
    return [_entry_to_dict(entry) for entry in EXPRESSION_KB]


def get_expression_by_phrase(phrase: str) -> Optional[dict]:
    query = phrase.strip().lower()
    for entry in EXPRESSION_KB:
        candidates = [entry.phrase, entry.canonical_name] + entry.synonyms + entry.example_queries
        if any(query == str(item).lower() for item in candidates):
            return _entry_to_dict(entry)
    return None


def search_expressions(query: str, limit: int = 10) -> list[dict]:
    query_lower = _normalize_text(query)
    if not query_lower:
        return []

    results = []
    seen = set()
    for entry in EXPRESSION_KB:
        if _expression_matches_query(entry, query_lower):
            if entry.id in seen:
                continue
            seen.add(entry.id)
            results.append(_entry_to_dict(entry))
    return sorted(
        results,
        key=lambda item: (-_expression_score(item, query_lower), -len(item.get("phrase", ""))),
    )[:limit]


def classify_expression(query: str) -> dict:
    matches = search_expressions(query, limit=8)
    if not matches:
        return {
            "query": query,
            "matched": [],
            "best_match": None,
            "route_intent": ["manual_review"],
            "route_to": ["manual_review"],
            "leakage_warning": False,
            "matched_layers": [],
        }

    best = _pick_best_match(query, matches)
    route_intent = best.get("route_intent", [])
    route_to = best.get("route_to", [])
    leakage_warning = any(item.get("leakage_risk") for item in matches)
    return {
        "query": query,
        "matched": matches,
        "best_match": best,
        "route_intent": route_intent,
        "route_to": route_to,
        "leakage_warning": leakage_warning,
        "matched_layers": sorted({item.get("layer", "") for item in matches if item.get("layer")}),
    }


def _pick_best_match(query: str, matches: list[dict]) -> dict:
    query_lower = _normalize_text(query)
    exact = [item for item in matches if _normalize_text(item.get("phrase", "")) in query_lower or _normalize_text(item.get("canonical_name", "")) in query_lower]
    if exact:
        return sorted(exact, key=lambda item: len(item.get("phrase", "")), reverse=True)[0]
    target_priority = {
        "target_expression": 0,
        "condition_expression": 1,
        "factor_expression": 2,
        "metric_expression": 3,
        "sort_expression": 4,
        "intent_expression": 5,
    }
    return sorted(
        matches,
        key=lambda item: (
            target_priority.get(item.get("expression_type", ""), 99),
            -_expression_score(item, query_lower),
            len(item.get("phrase", "")),
        ),
    )[0]


def _normalize_text(text: str) -> str:
    text = (text or "").strip().lower()
    for ch in ["，", ",", "。", "；", ";", " ", "？", "?", "！", "!", "：", ":", "（", "）", "(", ")"]:
        text = text.replace(ch, "")
    return text


def _expression_matches_query(entry: ExpressionEntry, query_lower: str) -> bool:
    candidates = [
        entry.phrase,
        entry.canonical_name,
        entry.meaning,
        entry.formula,
    ] + entry.synonyms + entry.example_queries
    normalized_candidates = [_normalize_text(str(item)) for item in candidates]
    return any(
        candidate and (candidate in query_lower or query_lower in candidate)
        for candidate in normalized_candidates
    )


def _expression_score(entry: dict, query_lower: str) -> int:
    candidates = [
        entry.get("phrase", ""),
        entry.get("canonical_name", ""),
        entry.get("meaning", ""),
        entry.get("formula", ""),
    ] + entry.get("synonyms", []) + entry.get("example_queries", [])
    query_tokens = [token for token in _tokenize(query_lower) if token]
    best = 0
    for item in candidates:
        candidate = _normalize_text(str(item))
        if not candidate:
            continue
        score = 0
        if candidate in query_lower:
            score += len(candidate)
        if query_lower in candidate:
            score += max(1, len(query_lower))
        score += sum(1 for token in query_tokens if token and token in candidate)
        best = max(best, score)
    return best


def _tokenize(text: str) -> list[str]:
    tokens = []
    for sep in ["且", "和", "或", "与", "以及", "、"]:
        text = text.replace(sep, "|")
    for chunk in text.split("|"):
        chunk = chunk.strip()
        if chunk:
            tokens.append(chunk)
    return tokens


def _entry_to_dict(entry: ExpressionEntry) -> dict:
    result = entry.__dict__.copy()
    if not result.get("layer"):
        result["layer"] = _infer_layer(entry)
    return result


def _infer_layer(entry: ExpressionEntry) -> str:
    if entry.expression_type == "target_expression":
        return "target"
    if entry.expression_type == "metric_expression":
        return "composite_score"
    if entry.expression_type in {"condition_expression", "factor_expression"}:
        return "processed_factor"
    return ""


def list_expression_layers() -> dict[str, int]:
    counts: dict[str, int] = {}
    for entry in EXPRESSION_KB:
        layer = _entry_to_dict(entry).get("layer", "") or "unknown"
        counts[layer] = counts.get(layer, 0) + 1
    return dict(sorted(counts.items(), key=lambda item: item[0]))
